config/routes.rb
Operation::Application.routes.draw do
  devise_for :users

root to: 'posts#index'

  match '/galary' ,    to: 'home#galary'
  match '/about' ,    to: 'home#about'
  match '/contact' ,    to: 'home#contact'
  resources :posts 
  resources :users  

end

app/models/post.rb
class Post < ActiveRecord::Base
	attr_accessible :content, :title, :user_id
	validates :user_id, presence: true
	validates :content, presence: true
	validates :title, presence: true, length: { maximum: 140 }
	belongs_to :user
	default_scope order: 'posts.created_at DESC'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable
  if Rails.env.production?
  	devise :confirmable
  end

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :image_blob
  # attr_accessible :title, :body
  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def home
		@posts = Post.paginate(page: params[:page])
	end

	def galary
	end

	def about
	end

	def contact
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_filter :authenticate_user!,:except=>[:index]
	def index
		@posts = Post.paginate(page: params[:page])
		@post = Post.new
		@user = User.all
	end

	def destroy
		@post.destroy
		redirect_to root_url
	end

	def create
		@posts = Post.paginate(page: params[:page])
		@post = current_user.posts.build(params[:post])
		if @post.save
			flash[:success] = "Post created!"
			redirect_to root_url
		else
			render 'index'
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
# Returns the Gravatar (http://gravatar.com/) for the given user.
def gravatar_for(user,size)
	gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
	gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
	image_tag(gravatar_url, alt: user.name, class: "gravatar")
end
end

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<div class="row4">
<p >
<h4> Mobile Number:</h4>

						+91-9629171382 <br>

						<h4> Email:</h4>
						samuels410@gmail.com <br>
						samuel@arrivusystems.com <br>

						<h4> Facebook</h4>

						http://facebook.com/samuels410

						<h4> Address For Communication:</h4>
						Y.samuel santhosh ,<br>
						Zionpuram, <br>
						M.K.Pottal Post, <br>
						Kanyakumari District, <br>
						629501. <br>
.
</p>
</div>

app/views/home/galary.html.erb
<ul class="thumbnails" align="center">
  <li class="span6">
    <div class="thumbnail" align="center">
      <%= link_to image_tag("g1.jpg")%>
      <h5>Madu,jack,pig,tamil</h5>
    </div>
  </li>
  <li class="span6">
    <div class="thumbnail" align="center">
      <%= link_to image_tag("g8.jpg")%>
      <h5>Shiek,jose,me</h5>
    </div>
  </li>
  <li class="span6">
    <div class="thumbnail" align="center">
      <%= link_to image_tag("g3.jpg")%>
      <h5>Darjeeling Iv</h5>
    </div>
  </li>
  <li class="span6">
    <div class="thumbnail" align="center">
      <%= link_to image_tag("g4.jpg")%>
      <h5>Darjeeling Iv</h5>
    </div>
  </li>
  <li class="span6">
    <div class="thumbnail" align="center">
      <%= link_to image_tag("g5.jpg")%>
      <h5>Darjeeling Iv</h5>
    </div>
  </li>
  <li class="span6">
    <div class="thumbnail" align="center">
      <%= link_to image_tag("g6.jpg")%>
      <h5>Darjeeling Iv</h5>
    </div>
  </li>
  <li class="span6">
    <div class="thumbnail" align="center">
      <%= link_to image_tag("g7.jpg")%>
      <h5>Darjeeling Iv</h5>
    </div>
  </li>
  <li class="span6">
    <div class="thumbnail" align="center">
      <%= link_to image_tag("g2.jpg")%>
      <h5>Darjeeling Iv</h5>
    </div>
  </li>
</ul>

app/views/home/home.html.erb
<div align="center">

	<div class="alert alert-success">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		<strong>Welcome! </strong> Friend Have a nice day...
	</div>
</div><br>
<div id="myCarousel" class="carousel slide" >
	
	<!-- Carousel items -->
	<div class="carousel-inner" >
		<div class="active item"  >
			<%=image_tag("1.jpg", alt: "sam",class: "img1")%>
		</div>	
		<div class="item">
			<%=image_tag("2.jpg", alt: "sam",class: "img1")%>
		</div>
		<div class="item">
			<%=image_tag("3.jpg", alt: "sam",class: "img1")%>
		</div>
		<div class="item">
			<%=image_tag("4.jpg", alt: "sam",class: "img1")%>
		</div>
		<div class="item">
			<%=image_tag("5.jpg", alt: "sam",class: "img1")%>
		</div>
		<div class="item">
			<%=image_tag("6.jpg", alt: "sam",class: "img1")%>
		</div>
	</div>

	<!-- Carousel nav -->
	<a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
	<a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>

</div>
<script type="text/javascript">
$('.carousel').carousel({
	interval: 2000

})

setTimeout(function () {
	$('.alert').alert('close')
}, 5000)

</script>

app/views/layouts/_about.html.erb
<!-- Button to trigger modal -->
<title>samuel santhosh | About Me</title>
<!-- Modal -->
<div id="myModal1" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel" align="center">Y.samuel santhosh</h3>
  </div>
  <div class="modal-body">

    <div class="accordion" id="accordion2">

      <div class="accordion-group">
        <div class="accordion-heading">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
           Work
         </a>
       </div>
       <div id="collapseOne" class="accordion-body collapse in">
        <div class="accordion-inner">
          Hi, I like to developing Web Applications using microsoft technologies like ASP.NET and opensource technologies  Ruby On Rails .Working as a web developer in Arrivu Systems.
         
          <br>
          Job Description:
          <br>
          web Applications developing using ruby on rails.
        </div>
      </div>
    </div>
    
    <div class="accordion-group">
      <div class="accordion-heading">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
          Under Graduate
        </a>
      </div>
      <div id="collapseTwo" class="accordion-body collapse">
        <div class="accordion-inner">
          I have compeleted B.E Computer Sciense in SNS COLLEGE OF TECHNOLOGY coimbatore.
          <br>
          Joined Year:2009
          <br>
          Completed Year:2012
        </div>
      </div>
    </div>

    <div class="accordion-group">
      <div class="accordion-heading">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseThree">
          Diploma
        </a>
      </div>
      <div id="collapseThree" class="accordion-body collapse">
        <div class="accordion-inner">
          I have compeleted Diploma in Computer Sciense in SREE KRISHNA POLYTECHNIC COLLEGE Nagercoil.
          <br>
          Joined Year:2006
          <br>
          Completed Year:2009
        </div>
      </div>
    </div>


    <div class="accordion-group">
      <div class="accordion-heading">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseFour">
          Schooling
        </a>
      </div>
      <div id="collapseFour" class="accordion-body collapse">
        <div class="accordion-inner">
          I did my schooling in LMS HIGHER SECONDARY ZIONPURAM
          <br>
          Completed Year:2006
        </div>
      </div>
    </div>


    <div class="modal-footer">
      <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>

    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<a href="https://facebook.com/samuels410">Follow me on Facebook</a>
		by samuel santhosh
	</small>
	<nav>
		<ul>
			<li><%= link_to "Photos",galary_path %></li>
			<li><%= link_to "Contact Me", contact_path %></li>
			<li><a href="http://lankasri.com">News</a></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar  navbar-fixed-top navbar-inverse ">
	<div class="navbar-inner">
		<div class="container">
			<h4 id="logo">Samuel santhosh</h4>
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to "Home", root_path %></li>
					<li><%= link_to "Galary", galary_path %></li>
					<li><a href="#myModal1" role="link"  data-toggle="modal">About Me</a></li>	
					<li><a href="#myModal" role="link"  data-toggle="modal">Contact</a></li>
					<% if user_signed_in? %>
					<li><%= link_to current_user.email ,edit_user_registration_path %>  </li>
					<li><%= link_to "Log out", destroy_user_session_path, method: "delete" %></li>
					<% else %>
					<li><%= link_to "Login", new_user_session_path %></li>
					<li><%= link_to "Create Account", new_user_registration_path %></li>
					<% end %>
				</ul>
			</nav>
		</div>
	</div>
	
</header>	

<div class="row1">
	<aside class="span2">

		<table>
			
			<tr><td>
				
			</td></tr>
			<tr><td>
				
				<!-- Button to trigger modal -->

				<!-- Modal -->
				<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
						<h3 id="myModalLabel" align="center">Contact me</h3>
					</div>
					<div class="modal-body hero-unit">
						<h4> Mobile Number:</h4>

						+91-9629171382 <br>

						<h4> Email:</h4>
						samuels410@gmail.com <br>
						samuel@arrivusystems.com <br>

						<h4> Facebook</h4>

						http://facebook.com/samuels410

						<h4> Address For Communication:</h4>
						Y.samuel santhosh ,<br>
						Zionpuram, <br>
						M.K.Pottal Post, <br>
						Kanyakumari District, <br>
						629501. <br>

					</div>
				</div>
			</td></tr>
			<tr><td>

				
				<!-- Button to trigger modal -->

				<!-- Modal -->
				<div id="myModal3" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
						<h3 id="myModalLabel" align="center">Photo Gallary </h3>
					</div>
					<div class="modal-body" align="center">

						<ul class="thumbnails" align="center">
							<li class="span6">
								<div class="thumbnail" align="center">
									<%= link_to image_tag("6.jpg")%>
									<h5>Freinds</h5>
								</div>
							</li>
							<li class="span6">
								<div class="thumbnail" align="center">
									<%= link_to image_tag("g2.jpg")%>
									<h5>Freinds</h5>
								</div>
							</li>
							<li class="span6">
								<div class="thumbnail" align="center">
									<%= link_to image_tag("g3.jpg")%>
									<h5>Freinds</h5>
								</div>
							</li>
							<li class="span6">
								<div class="thumbnail" align="center">
									<%= link_to image_tag("g4.jpg")%>
									<h5>Freinds</h5>
								</div>
							</li>
						</ul>


					</div>
					<div class="modal-footer">
						<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>


					</div>

				</div>

			</td></tr>


		</table>
	</aside>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head >
	<title>Welcome | samuel santhosh</title>
	<%= stylesheet_link_tag "application", media: "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>
		<%= render 'layouts/header' %>

</head>
<body .carousel('next')>

<div class="container">
<% flash.each do |key, value| %>
<div class="alert alert-<%= key %>"><%= value %></div>
<% end %>
<%= yield %>
<%= debug(params) if Rails.env.development? %>
<%= render 'layouts/footer' %>
<%= render 'layouts/about' %>
</div>
</body>
</html>

app/views/posts/_post.html.erb
<li>
<span class="title"> <b> <%= post.title %> </b></span>
<br>
<span class="content"><%= post.content %></span>
<span class="timestamp">
<%= post.user.email %>	
 Posted <%= time_ago_in_words(post.created_at) %> ago.
</span>
</li>

app/views/posts/index.html.erb
<div class="row">

	<div align="center">

		<div class="alert alert-success">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
			<strong>Welcome! </strong> Friend Have a nice day...
		</div>
	</div><br>
	<div id="myCarousel" class="carousel slide" >

		<!-- Carousel items -->
		<div class="carousel-inner" >
			<div class="active item"  >
				<%=image_tag("1.jpg", alt: "sam",class: "img1")%>
			</div>	
			<div class="item">
				<%=image_tag("2.jpg", alt: "sam",class: "img1")%>
			</div>
			<div class="item">
				<%=image_tag("3.jpg", alt: "sam",class: "img1")%>
			</div>
			<div class="item">
				<%=image_tag("4.jpg", alt: "sam",class: "img1")%>
			</div>
			<div class="item">
				<%=image_tag("5.jpg", alt: "sam",class: "img1")%>
			</div>
			<div class="item">
				<%=image_tag("6.jpg", alt: "sam",class: "img1")%>
			</div>
		</div>

		<!-- Carousel nav -->
		<a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
		<a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>

	</div>
	<script type="text/javascript">
	$('.carousel').carousel({
		interval: 2000

	})

	setTimeout(function () {
		$('.alert').alert('close')
	}, 5000)

	</script>

	<div class="span10 ">
		<h3>Posts(<%= @posts.count %>)</h3>
		<ol class="posts">
			<%= render @posts %>
		</ol>
		<%= will_paginate @posts %>
	</div>
	<div>
		<% if user_signed_in? %>
		<div class="row">
			<aside class="span10">
				<section>
					<br>
					<%= render 'shared/user_info' %>
				</section>
				<section>
					<%= render 'shared/post_form' %>
				</section>
			</aside>
		</div>
		<% else %>

		<% end %>
	</div>

</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
<div class="alert alert-error">
The form contains <%= pluralize(object.errors.count, "error") %>.
</div>
<ul>
<% object.errors.full_messages.each do |msg| %>
<li>* <%= msg %></li>
<% end %>
</ul>
</div>
<% end %>

app/views/shared/_post_form.html.erb
<%= form_for(@post) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
<%= f.text_field :title, placeholder: "Add Title" %>
<div class="field">
<%= f.text_area :content, placeholder: "Compose new post..." , :rows => 50, :cols => 600%>
</div>
<%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<div class="row">
<div class="span4">
	<a href="<%= user_path(current_user) %>">
		<%= gravatar_for current_user, size: 52 %>
	</a>
	<%= current_user.email %>
	<span>
		<%= link_to "view my profile", edit_user_registration_path %>
	</span>
	<span>
		<%= pluralize(current_user.posts.count, "Post") %>
	</span>
</div>
</div>